#!/usr/bin/env bash
set -euo pipefail
cd /wuqingyaoa800/qiuziyan/DiffSynth-Studio
export CUDA_VISIBLE_DEVICES=3
export TOKENIZERS_PARALLELISM=false
export DIFFSYNTH_SKIP_DOWNLOAD=true
export DIFFSYNTH_MODEL_BASE_PATH=/wuqingyaoa800/qiuziyan/DiffSynth-Studio/models
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
/wuqingyaoa800/qiuziyan/envs/diffsynth-qwen/bin/accelerate launch   /wuqingyaoa800/qiuziyan/DiffSynth-Studio/examples/qwen_image/model_training/train.py   --dataset_base_path "/wuqingyaoa800/qiuziyan/LoReflection_arch_p0/data/loreflection_qwen_arch_control_raw3dfront_clean_512_oob050"   --dataset_metadata_path "/wuqingyaoa800/qiuziyan/LoReflection_arch_p0/data/loreflection_qwen_arch_control_raw3dfront_clean_512_oob050/metadata.csv"   --data_file_keys "image,context_image"   --max_pixels 262144   --dataset_repeat 1   --per_device_batch_size 1   --dataset_num_workers 1   --model_id_with_origin_paths "Qwen/Qwen-Image:transformer/diffusion_pytorch_model*.safetensors,Qwen/Qwen-Image:text_encoder/model*.safetensors,Qwen/Qwen-Image:vae/diffusion_pytorch_model.safetensors"   --fp8_models "Qwen/Qwen-Image:transformer/diffusion_pytorch_model*.safetensors,Qwen/Qwen-Image:text_encoder/model*.safetensors,Qwen/Qwen-Image:vae/diffusion_pytorch_model.safetensors"   --offload_models "Qwen/Qwen-Image:text_encoder/model*.safetensors,Qwen/Qwen-Image:vae/diffusion_pytorch_model.safetensors"   --learning_rate 5e-5   --num_epochs 1   --save_steps 1000   --seed 42   --console_log_interval 20   --tensorboard_log_interval 20   --metrics_jsonl_path "/wuqingyaoa800/qiuziyan/LoReflection_arch_p0/reports/full_clean_512_oob050_20260629_191553/train_metrics_qwen_arch_raw3dfront_clean512_oob050_rank64_fp8exact_cuda_20260629_210803.jsonl"   --remove_prefix_in_ckpt "pipe.dit."   --output_path "/wuqingyaoa800/qiuziyan/LoReflection_arch_p0/models/train/qwen_arch_raw3dfront_clean512_oob050_rank64_fp8exact_cuda_20260629_210803"   --lora_base_model "dit"   --lora_target_modules "to_q,to_k,to_v,add_q_proj,add_k_proj,add_v_proj,to_out.0,to_add_out,img_mlp.net.2,img_mod.1,txt_mlp.net.2,txt_mod.1"   --lora_rank 64   --lora_checkpoint "/wuqingyaoa800/qiuziyan/DiffSynth-Studio/models/DiffSynth-Studio/Qwen-Image-In-Context-Control-Union/model.safetensors"   --extra_inputs "context_image"   --use_gradient_checkpointing   --use_gradient_checkpointing_offload   --find_unused_parameters   2>&1 | tee "/wuqingyaoa800/qiuziyan/LoReflection_arch_p0/logs/qwen_arch_raw3dfront_clean512_oob050_rank64_fp8exact_cuda_20260629_210803.log"
